--
-- Script was generated by Devart dbForge Data Pump for SQL Server, Version 1.3.57.0
-- Product home page: http://www.devart.com/dbforge/sql/data-pump
-- Script date 5/21/2018 5:13:47 PM
-- Server version: 10.00.1600
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT DiskHouse.dbo.users ON
GO
INSERT DiskHouse.dbo.users(Id, Name, Password, Rights) VALUES (1, N'LP', N'rock', N'2')
INSERT DiskHouse.dbo.users(Id, Name, Password, Rights) VALUES (2, N'admin', N'admin', N'1')
INSERT DiskHouse.dbo.users(Id, Name, Password, Rights) VALUES (3, N'guest', N'guest', N'3')
INSERT DiskHouse.dbo.users(Id, Name, Password, Rights) VALUES (8, N'ak', N'ak12', N'2')
INSERT DiskHouse.dbo.users(Id, Name, Password, Rights) VALUES (9, N'satyr', N'pagan', N'2')
INSERT DiskHouse.dbo.users(Id, Name, Password, Rights) VALUES (10, N'HG', N'invisible', N'2')
INSERT DiskHouse.dbo.users(Id, Name, Password, Rights) VALUES (11, N'X', N'dawg', N'2')
INSERT DiskHouse.dbo.users(Id, Name, Password, Rights) VALUES (12, N'ND', N'213', N'2')
INSERT DiskHouse.dbo.users(Id, Name, Password, Rights) VALUES (13, N'AT', N'pass', N'2')
INSERT DiskHouse.dbo.users(Id, Name, Password, Rights) VALUES (18, N'M&M', N'D12', N'2')
GO
SET IDENTITY_INSERT DiskHouse.dbo.users OFF
GO