--
-- Script was generated by Devart dbForge Data Pump for SQL Server, Version 1.3.57.0
-- Product home page: http://www.devart.com/dbforge/sql/data-pump
-- Script date 5/21/2018 5:13:47 PM
-- Server version: 10.00.1600
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT DiskHouse.dbo.artists ON
GO
INSERT DiskHouse.dbo.artists(Id, Name, Description, Members, userid) VALUES (1, N'Linkin Park', N'Rock band', N'Chester,', 1)
INSERT DiskHouse.dbo.artists(Id, Name, Description, Members, userid) VALUES (3, N'Alan&Kepa', N'Rap', N'Alan, Kepa', 8)
INSERT DiskHouse.dbo.artists(Id, Name, Description, Members, userid) VALUES (4, N'Faun', N'Folk', N'Oliver SaTyr, Fiona Ruggenberg, Niel Mitra', 9)
INSERT DiskHouse.dbo.artists(Id, Name, Description, Members, userid) VALUES (5, N'Haggard', N'folk', N'lalal', 10)
INSERT DiskHouse.dbo.artists(Id, Name, Description, Members, userid) VALUES (6, N'Nate Dogg', N'G-Funk', N'Nate Dogg', 12)
INSERT DiskHouse.dbo.artists(Id, Name, Description, Members, userid) VALUES (7, N'Xzibit', N'Rap', N'Xzibit', 11)
INSERT DiskHouse.dbo.artists(Id, Name, Description, Members, userid) VALUES (9, N'Eminem', N'Rap', N'Eminem,Marshall Mathers, Slim Shady', 18)
INSERT DiskHouse.dbo.artists(Id, Name, Description, Members, userid) VALUES (10, N'Wu Tang Clan', N'Rap', N'RZA, GZA, ODB, Method Man, Raekwon, Ghostface Killah', 3)
INSERT DiskHouse.dbo.artists(Id, Name, Description, Members, userid) VALUES (11, N'Nujabes', N'Jazz Rap', N'Jun Seba', 3)
INSERT DiskHouse.dbo.artists(Id, Name, Description, Members, userid) VALUES (12, N'Heilung', N'Nordic Folk', N'Maria Franz, Christopher Juul, Kai Uwe Faust', 3)
INSERT DiskHouse.dbo.artists(Id, Name, Description, Members, userid) VALUES (13, N'Paddy and the Rats', N'Celtic Punk', N'Vince Murphy, Paddy O''Reilly, Sam McKenzie', 3)
INSERT DiskHouse.dbo.artists(Id, Name, Description, Members, userid) VALUES (14, N'Pacha Man', N'Reggae-Rap', N'Pacha Man', 3)
INSERT DiskHouse.dbo.artists(Id, Name, Description, Members, userid) VALUES (15, N'Ghost', N'Heavy Metal', N'Tobias Forge', 3)
INSERT DiskHouse.dbo.artists(Id, Name, Description, Members, userid) VALUES (16, N'Agnes Obel', N'Classical/Folk', N'Agnes Obel', 3)
GO
SET IDENTITY_INSERT DiskHouse.dbo.artists OFF
GO