--
-- Script was generated by Devart dbForge Data Pump for SQL Server, Version 1.3.57.0
-- Product home page: http://www.devart.com/dbforge/sql/data-pump
-- Script date 5/21/2018 5:13:47 PM
-- Server version: 10.00.1600
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT DiskHouse.dbo.Albums ON
GO
INSERT DiskHouse.dbo.Albums(Id, Name, Year, Genre, [Artist.Id]) VALUES (1, N'Meteora', '2016-01-01', N'Rap', 1)
INSERT DiskHouse.dbo.Albums(Id, Name, Year, Genre, [Artist.Id]) VALUES (8, N'Eden', '2011-01-01', N'Folk', 4)
INSERT DiskHouse.dbo.Albums(Id, Name, Year, Genre, [Artist.Id]) VALUES (10, N'Tabu', '2012-01-01', N'Rap', 3)
INSERT DiskHouse.dbo.Albums(Id, Name, Year, Genre, [Artist.Id]) VALUES (11, N'Music & Me', '2001-01-01', N'G-Funk', 6)
INSERT DiskHouse.dbo.Albums(Id, Name, Year, Genre, [Artist.Id]) VALUES (13, N'Oxigen', '2016-01-01', N'Rap', 3)
INSERT DiskHouse.dbo.Albums(Id, Name, Year, Genre, [Artist.Id]) VALUES (16, N'At The Speed Of Life', '1996-01-01', N'Gangsta Rap', 7)
INSERT DiskHouse.dbo.Albums(Id, Name, Year, Genre, [Artist.Id]) VALUES (21, N'Philharmonics', '2010-04-10', N'Classical', 16)
INSERT DiskHouse.dbo.Albums(Id, Name, Year, Genre, [Artist.Id]) VALUES (22, N'Agnes', '2013-09-30', N'Folk', 16)
INSERT DiskHouse.dbo.Albums(Id, Name, Year, Genre, [Artist.Id]) VALUES (23, N'Marshall Mathers LP', '2000-03-01', N'Rap', 9)
INSERT DiskHouse.dbo.Albums(Id, Name, Year, Genre, [Artist.Id]) VALUES (24, N'Recovery', '2010-04-02', N'Rap', 9)
INSERT DiskHouse.dbo.Albums(Id, Name, Year, Genre, [Artist.Id]) VALUES (25, N'Marshall Mathers LP2', '2013-12-06', N'Rap', 9)
INSERT DiskHouse.dbo.Albums(Id, Name, Year, Genre, [Artist.Id]) VALUES (26, N'Midgard', '2016-08-19', N'Pop', 4)
INSERT DiskHouse.dbo.Albums(Id, Name, Year, Genre, [Artist.Id]) VALUES (27, N'Meliora', '2015-08-21', N'Heavy Metal', 15)
INSERT DiskHouse.dbo.Albums(Id, Name, Year, Genre, [Artist.Id]) VALUES (28, N'Awaken the Centuries', '2000-02-07', N'Symphonic Metal', 5)
INSERT DiskHouse.dbo.Albums(Id, Name, Year, Genre, [Artist.Id]) VALUES (29, N'Eppur Si Muove', '2004-04-26', N'Symphonic Metal', 5)
INSERT DiskHouse.dbo.Albums(Id, Name, Year, Genre, [Artist.Id]) VALUES (30, N'Tales of Ithiria', '2018-08-29', N'Death-Doom', 5)
INSERT DiskHouse.dbo.Albums(Id, Name, Year, Genre, [Artist.Id]) VALUES (31, N'Lifa', '2018-02-05', N'Nordic Folk', 12)
INSERT DiskHouse.dbo.Albums(Id, Name, Year, Genre, [Artist.Id]) VALUES (32, N'Minutes To Midnight', '2007-04-14', N'Rock', 1)
INSERT DiskHouse.dbo.Albums(Id, Name, Year, Genre, [Artist.Id]) VALUES (33, N'G-Funk Classics', '1998-02-06', N'G-Funk', 6)
INSERT DiskHouse.dbo.Albums(Id, Name, Year, Genre, [Artist.Id]) VALUES (34, N'Metaphorical Music', '2003-08-21', N'Jazz- Hop', 11)
INSERT DiskHouse.dbo.Albums(Id, Name, Year, Genre, [Artist.Id]) VALUES (35, N'Spiritual State', '2011-03-12', N'Jazz-Rap', 11)
INSERT DiskHouse.dbo.Albums(Id, Name, Year, Genre, [Artist.Id]) VALUES (36, N'Drumul catre rastafari', '2003-04-20', N'Raggae', 14)
INSERT DiskHouse.dbo.Albums(Id, Name, Year, Genre, [Artist.Id]) VALUES (37, N'Contra curentului', '2005-02-07', N'Raggae-Rap', 14)
INSERT DiskHouse.dbo.Albums(Id, Name, Year, Genre, [Artist.Id]) VALUES (38, N'Rats on Board', '2009-09-01', N'Pub Rock', 13)
INSERT DiskHouse.dbo.Albums(Id, Name, Year, Genre, [Artist.Id]) VALUES (39, N'Enter the Wu-Tang (36 Chambers)', '1993-09-09', N'Hip-Hop', 10)
INSERT DiskHouse.dbo.Albums(Id, Name, Year, Genre, [Artist.Id]) VALUES (41, N'Weapons of Mass Destruction', '2004-02-01', N'Gangsta Rap', 7)
GO
SET IDENTITY_INSERT DiskHouse.dbo.Albums OFF
GO