--
-- Script was generated by Devart dbForge Data Pump for SQL Server, Version 1.3.57.0
-- Product home page: http://www.devart.com/dbforge/sql/data-pump
-- Script date 5/21/2018 5:13:47 PM
-- Server version: 10.00.1600
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT DiskHouse.dbo.awards ON
GO
INSERT DiskHouse.dbo.awards(Id, Name, [Album.Id], Year) VALUES (3, N'Best Album', 10, '2018-01-01')
INSERT DiskHouse.dbo.awards(Id, Name, [Album.Id], Year) VALUES (4, N'Best Song in Ablum', 10, '2018-01-01')
INSERT DiskHouse.dbo.awards(Id, Name, [Album.Id], Year) VALUES (6, N'Danish Pop Album of the Year', 21, '2016-06-02')
INSERT DiskHouse.dbo.awards(Id, Name, [Album.Id], Year) VALUES (7, N'Danish Album of the Year', 21, '2017-01-05')
INSERT DiskHouse.dbo.awards(Id, Name, [Album.Id], Year) VALUES (8, N'Grammis Award for Hard Rock of the Year', 27, '2015-08-21')
INSERT DiskHouse.dbo.awards(Id, Name, [Album.Id], Year) VALUES (9, N'Nominated:Best International Rock Group', 1, '2016-01-01')
INSERT DiskHouse.dbo.awards(Id, Name, [Album.Id], Year) VALUES (10, N'MTV Music Award for Best Album', 32, '2007-01-01')
GO
SET IDENTITY_INSERT DiskHouse.dbo.awards OFF
GO